2022-06-15 23:50:49,118 INFO    MainThread:14916 [wandb_setup.py:_flush():75] Loading settings from /home/aditta/.config/wandb/settings
2022-06-15 23:50:49,119 INFO    MainThread:14916 [wandb_setup.py:_flush():75] Loading settings from /media/aditta/UBUNTU/feedback-prize-effectiveness/code/wandb/settings
2022-06-15 23:50:49,119 INFO    MainThread:14916 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-06-15 23:50:49,119 INFO    MainThread:14916 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'trainer.py', 'program': 'trainer.py'}
2022-06-15 23:50:49,119 INFO    MainThread:14916 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-06-15 23:50:49,120 INFO    MainThread:14916 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-06-15 23:50:49,120 INFO    MainThread:14916 [wandb_init.py:_log_setup():405] Logging user logs to /media/aditta/UBUNTU/feedback-prize-effectiveness/code/wandb/run-20220615_235049-164nv2je/logs/debug.log
2022-06-15 23:50:49,121 INFO    MainThread:14916 [wandb_init.py:_log_setup():406] Logging internal logs to /media/aditta/UBUNTU/feedback-prize-effectiveness/code/wandb/run-20220615_235049-164nv2je/logs/debug-internal.log
2022-06-15 23:50:49,121 INFO    MainThread:14916 [wandb_init.py:init():439] calling init triggers
2022-06-15 23:50:49,121 INFO    MainThread:14916 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-06-15 23:50:49,122 INFO    MainThread:14916 [wandb_init.py:init():492] starting backend
2022-06-15 23:50:49,122 INFO    MainThread:14916 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-15 23:50:49,146 INFO    MainThread:14916 [backend.py:ensure_launched():219] starting backend process...
2022-06-15 23:50:49,157 INFO    MainThread:14916 [backend.py:ensure_launched():224] started backend process with pid: 14949
2022-06-15 23:50:49,160 INFO    MainThread:14916 [wandb_init.py:init():501] backend started and connected
2022-06-15 23:50:49,168 INFO    MainThread:14916 [wandb_init.py:init():565] updated telemetry
2022-06-15 23:50:49,171 INFO    MainThread:14916 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-06-15 23:50:54,748 INFO    MainThread:14916 [wandb_run.py:_on_init():1759] communicating current version
2022-06-15 23:50:55,271 INFO    MainThread:14916 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.18 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-06-15 23:50:55,272 INFO    MainThread:14916 [wandb_init.py:init():625] starting run threads in backend
2022-06-15 23:50:55,680 INFO    MainThread:14916 [wandb_run.py:_console_start():1733] atexit reg
2022-06-15 23:50:55,683 INFO    MainThread:14916 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-06-15 23:50:55,683 INFO    MainThread:14916 [wandb_run.py:_redirect():1611] Redirecting console.
2022-06-15 23:50:55,685 INFO    MainThread:14916 [wandb_run.py:_redirect():1667] Redirects installed.
2022-06-15 23:50:55,685 INFO    MainThread:14916 [wandb_init.py:init():664] run started, returning control to user process
2022-06-15 23:51:15,059 INFO    MainThread:14916 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 255
2022-06-15 23:51:15,061 INFO    MainThread:14916 [wandb_run.py:_restore():1674] restore
